name: Update Spring Test Version

on:
  push:
    branches:
      - main

jobs:
  update-spring-test:
    runs-on: ubuntu-latest

    env:
      NEW_VERSION: "4.3.28.RELEASE"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Update Spring Test Version
      run: |
        # Find and update pom.xml files
        find . -name 'pom.xml' -type f -exec sed -i "s|<artifactId>spring-test<\/artifactId>\(.*\)<version>.*<\/version>|<artifactId>spring-test<\/artifactId>\1<version>${{ env.NEW_VERSION }}<\/version>|" {} +
        find . -name 'pom.xml' -type f -exec cat {} \;
    - name: Commit and Push Changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update spring-test version to ${NEW_VERSION}" && git push origin ${{ github.ref }}
