name: Update Spring Test Version

on:
  push:
    branches:
      - master

jobs:
  update-spring-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install xmlstarlet
      run: sudo apt-get update && sudo apt-get install -y xmlstarlet

    - name: Set New Version
      run: echo "NEW_VERSION=4.3.28.RELEASE" >> $GITHUB_ENV

    - name: Update Spring Test Version
      run: |
        xmlstarlet ed -L -N pom="http://maven.apache.org/POM/4.0.0" \
          --update "//pom:dependency[pom:artifactId='spring-test']/pom:version" \
          --value "${NEW_VERSION}" pom.xml

    - name: Commit and Push Changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -m "Update spring-test version to ${NEW_VERSION}" && git push origin ${{ github.ref }}
